### ISSUE TITLE
请问下如何获取账户的EOS余额

### ISSUE THREAD

**Issue by hbzou17** [myxtype/eos-client#2]
<?php
require 'vendor/autoload.php';

use xtype\Eos\Client as EosClient;

$BASE_URL = "http://api-kylin.eosasia.one"; 

$client = new EosClient([
    'base_uri' => $BASE_URL,
    'timeout' => 30,
]);
 
$chain = $client->chain();
// You can do this
// will visit http://api-kylin.eosasia.one/v1/chain/get_info
 
var_dump($client->chain()->get_info()->chain_id);
var_dump($client->chain()->get_info()->last_irreversible_block_num);
var_dump($client->chain()->get_currency_balance("eosio.token", "teststorm222", "EOS"));

?>

输出报错：

string(64) "5fff1dae8dc8e2fc4d5b23b2c7665c97f9e9d8edf2b6485a86ba311c25639191"
int(44346698)
PHP Fatal error:  Uncaught Exception: Fail to retrieve account for  in /home/works/eosphp/vendor/myxtype/eos-client/src/Eos/Client.php:259
Stack trace:
#0 /home/works/eosphp/vendor/myxtype/eos-client/src/Eos/Plugin.php(43): xtype\Eos\Client->request('/v1/chain/get_c...', Array)
#1 /home/works/eosphp/eos.offline.php(22): xtype\Eos\Plugin->__call('get_currency_ba...', Array)
#2 {main}
  thrown in /home/works/eosphp/vendor/myxtype/eos-client/src/Eos/Client.php on line 259

**Comment by hbzou17** [comment]
报错代码：
 var_dump($client->chain()->get_currency_balance("eosio.token", "teststorm222", "EOS"));

**Comment by myxtype** [comment]
全部方法的参数请使用数组形式：
get_currency_balance(['code' => 'eosio.token', 'account' => 'teststorm222', 'symbol' => 'EOS']);

**Comment by myxtype** [comment]
另外，各个版本的接口方法/参数都不一致，你需要看清你现在链接的那一个节点是什么版本的，然后根据EOS官方文档进行调整。

**Comment by hbzou17** [comment]
非常感谢，建议加入 examples
